init: depend on libselinux
In file included from device/motorola/surnia/init/init_surnia.cpp:38:
system/core/init/util.h:29:10: fatal error: 'selinux/label.h' file not found

also, updated with this
https://github.com/halogenOS/android_device_oneplus_oneplus2/commit/3a199ba21cf3eaa55a84d34b4c1025f90f0381fa